title: Cloud Blog from rbashish
remote_theme: "wowthemesnet/mediumish-theme-jekyll8"
#theme: minima
author: rbashish
email: blog@rbashish.tech
description: > # this means to ignore newlines until "baseurl:"
  A Public Cloud Expert and a technology analyst who is always willing to learn and grow
  This blog is an example and he likes to write about cloud Technologies.
  Find more way to connect with him on different social network
permalink: /:title/
url                      : https://git.rbashish.tech 
baseurl                  : "/blog"
repository               : "rbashish/blog"

# Outputting

paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# social links
twitter_username: aashishlive # DO NOT include the @ character, or else the build will fail!
github_username:  rbashish # DO NOT include the @ character, or else the build will fail!
linkedin_username: rbashish

show_excerpts: true # set to false to remove excerpts on the homepage
show_sidebar: true 
