title: Cloud Blog from rbashish
#remote_theme: minimal-mistakes-jekyll
theme: minima
author: rbashish
email: blog@rbashish.tech
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: /blog
defaults:
  # _posts
  - scope:
      path: "/blog"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# social links
twitter_username: aashishlive # DO NOT include the @ character, or else the build will fail!
github_username:  rbashish # DO NOT include the @ character, or else the build will fail!
linkedin_username: rbashish

show_excerpts: true # set to false to remove excerpts on the homepage
show_sidebar: true 
