title: Cloud Blog from rbashish
#remote_theme: rundocs/jekyll-rtd-theme
theme: minima
author: rbashish
email: blog@rbashish.tech
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: ""
#baseurl: "git.rbashish.tech/blog"

# social links
twitter_username: aashishlive # DO NOT include the @ character, or else the build will fail!
github_username:  rbashish # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
show_sidebar: true 
